version: '3.9'

services:
  chat-mongo-test:
    image: mongo:5.0.7
    container_name: chat-mongo-test
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo --quiet | grep 1
      interval: 30s
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    ports:
      - 27018:27017

  chat-api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      chat-mongo-test:
        condition: service_healthy
    environment:
      - DATABASE_URL_TEST=mongodb://chat-mongo-test:27017/chat-test
      - NODE_ENV=TEST
